app:
  environment:
    - PYTHONUNBUFFERED=1
  build: .
  command: python3 -u app.py
  ports:
    - "5000:5000"
  volumes:
    - .:/myretailapp
  links:
    - db
db:
  image: mongo:latest
  hostname: myretail_mongodb
  environment:
    - MONGO_INITDB_DATABASE=MY_RETAIL
  volumes:
    - ./init-db.js:/docker-entrypoint-initdb.d/init-db.js:ro
  ports:
    - 27017:2701
